backend:
  name: git-gateway
  branch: master 

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog" 
    folder: "src/data/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Key", name: "key", widget: "hidden", default: "blog"} // for easy querying
      - {label: "Title", name: "title", widget: "string"}
      - {label: "AuthorImage", name: "authorimage", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "product"
    label: "Product"
    folder: "src/data/products"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields: 
      - {label: "Key", name: "key", widget: "hidden", default: "products"} // for easy querying
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "content", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "pages"
    label: "Pages"
    files: 
      - file: "src/data/index.md"
        label: "Homepage"
        name: "homepage"
        editor:
          preview: false
        fields: 
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}
          - {
            label: "HomeJumbo", name: "homejumbo", widget: "object",
            fields:
              [{label: "Image", name: "image", widget: "image"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Content", name: "content", widget: "string"}]
          }

      - file: "src/data/specializations.md"
        label: "Specializations"
        name: "specializations"
        editor:
          preview: false
        fields: 
          - {
            label: "Specializations",
            name: "specializations",
            widget: "list",
            field: {label: "Name", name: "name", widget: "string"}
          }

      - file: "src/data/aboutpage.md"
        label: "AboutPage"
        name: "aboutpage"
        editor:
          preview: false
        fields: 
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "content", widget: "string"}

      - file: "src/data/partners.md"
        label: "Partners"
        name: "partners"
        editor:
          preview: false
        fields: 
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Title", name: "title", widget: "string"}